name: ci
on:
  workflow_dispatch:
  push:
    branches: [ ng ]
  pull_request:
jobs:
 linux:
    uses: torporsche/appimage-builder/.github/workflows/main.yml@main
# macOS:
#    uses: minecraft-linux/macos-builder/.github/workflows/main.yml@main
